version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lxml
    versions:
    - 4.6.2
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: scrapy
    versions:
    - 2.4.1
